# Generated by Django 6.0 on 2026-01-07 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narocnine', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
