# Generated by Django 6.0 on 2026-01-07 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('narocnine', '0002_alter_appointment_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table='appointments',
        ),
        migrations.AlterModelTable(
            name='location',
            table='locations',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
